# Generated by Django 2.2.6 on 2020-10-24 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='Avatar/deafult-profile-image.png', upload_to='Avatar')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9500, verbose_name='العنوان')),
                ('image', models.ImageField(upload_to='Images', verbose_name='صورة مناسبة')),
                ('source', models.CharField(max_length=200, verbose_name='المصدر')),
                ('body', tinymce.models.HTMLField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.author')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comment_put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('avatar_commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.author')),
                ('user_comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_put', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Blog_Post')),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='category',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='website.Categories'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='website.Blog_Post'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='website.Blog_Post'),
        ),
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='Images_Apps')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='website.Categories')),
            ],
        ),
    ]
